version: '3'
services:
  server-1:
    build: ../server
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USERNAME: "sowmya"
      POSTGRES_DATABASE: "notes"
      POSTGRES_HOST: "notes-postgres.cgec0xq22d3g.us-east-1.rds.amazonaws.com"
      POSTGRES_PORT: "5432"
    command: ["npm","run","dev"]

  server-2:
    build: ../server
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USERNAME: "sowmya"
      POSTGRES_DATABASE: "notes"
      POSTGRES_HOST: "notes-postgres.cgec0xq22d3g.us-east-1.rds.amazonaws.com"
      POSTGRES_PORT: "5432"
    command: ["npm","run","dev"]

  server-3:
    build: ../server
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USERNAME: "sowmya"
      POSTGRES_DATABASE: "notes"
      POSTGRES_HOST: "notes-postgres.cgec0xq22d3g.us-east-1.rds.amazonaws.com"
      POSTGRES_PORT: "5432"
    command: ["npm","run","dev"]
    
  nginx:
    build: .
    depends_on:
      - server-1
      - server-2
      - server-3
    ports:
      - '8000:8000'
    restart: always  

  client:
    build: 
      context: ../client
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
             